# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10000, null=True)),
                ('department', models.CharField(blank=True, max_length=10000, null=True)),
                ('roomNo', models.CharField(blank=True, max_length=10000, null=True)),
                ('relation', models.CharField(blank=True, max_length=10000, null=True)),
                ('option', models.CharField(blank=True, max_length=10000, null=True)),
                ('phone', models.CharField(blank=True, max_length=10000, null=True)),
                ('address', models.CharField(blank=True, max_length=10000, null=True)),
                ('adhar', models.CharField(blank=True, max_length=10000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='opd',
            name='adhar',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='opd',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
